from wallet import *

# sending some coins from the first(index 0) account to second(index 1) account
coin = ETH
account = privateKeyToAccount(ETH, coins[ETH][0]['privkey'])
# I am sending to second wallet address(index 1) generated by 12 menumonic phrase
to = '0xebcceDE0B93d33E975afAc529b7306a9403D4Ee8'
amount = 2222222222222222222

send_tx(coin, account, to, amount)




